// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pact_run_cpp
void pact_run_cpp(std::string trees_file, std::string param_file, std::string output_prefix);
RcppExport SEXP _pact_pact_run_cpp(SEXP trees_fileSEXP, SEXP param_fileSEXP, SEXP output_prefixSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type trees_file(trees_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type param_file(param_fileSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_prefix(output_prefixSEXP);
    pact_run_cpp(trees_file, param_file, output_prefix);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pact_pact_run_cpp", (DL_FUNC) &_pact_pact_run_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
