# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run PACT analysis
#'
#' Runs the full PACT (Posterior Analysis of Coalescent Trees) pipeline on a
#' set of phylogenetic trees. Results are written to output files.
#'
#' @param trees_file Path to the NEWICK tree file (e.g., from BEAST or Migrate).
#' @param param_file Path to the PACT parameter file.
#' @param output_prefix Full path prefix for output files. The function appends
#'   \code{.stats}, \code{.tips}, \code{.skylines}, \code{.rules}, and
#'   \code{.pairs} to this prefix.
#'
#' @return Invisibly returns \code{NULL}. Output is written to files.
#'
#' @export
pact_run_cpp <- function(trees_file, param_file, output_prefix) {
    invisible(.Call(`_pact_pact_run_cpp`, trees_file, param_file, output_prefix))
}

